name: Build APK


on:
  push:                    # запускать при каждой загрузке кода
  workflow_dispatch:       # и по кнопке вручную


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4


      - name: Собрать APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug


      - name: Загрузить готовый APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk

